--Rellenamos las tablas creadas con algunos valores 

INSERT INTO CLIENT (CLIENT_ID, ACCOUNT_ID, AGE, COUNTRY, CLIENT_NAME) VALUES (1,1, 21, "España", "Claudio");
INSERT INTO CLIENT (CLIENT_ID, ACCOUNT_ID, AGE, COUNTRY, CLIENT_NAME) VALUES (2,2, 22, "Portugal", "Luis");
INSERT INTO CLIENT (CLIENT_ID, ACCOUNT_ID, AGE, COUNTRY, CLIENT_NAME) VALUES (3,3, 23, "Francia", "Charles");

INSERT INTO ACCOUNT (CLIENT_ID, ACCOUNT_ID, DEPOSIT, LOANS) VALUES (1,1, 100000, 0);
INSERT INTO ACCOUNT (CLIENT_ID, ACCOUNT_ID, DEPOSIT, LOANS) VALUES (2,2, 200000, 1000);
INSERT INTO ACCOUNT (CLIENT_ID, ACCOUNT_ID, DEPOSIT, LOANS) VALUES (3,3, 250000, 3000);

INSERT INTO TRANSACTIONS(CLIENT_ID, ACCCOUNT_ID, ACCOUNT_SECONDARY, CREDIT, CAUSE) VALUES (1,1,2, 1000, "Gastos taller");
INSERT INTO TRANSACTIONS(CLIENT_ID, ACCCOUNT_ID, ACCOUNT_SECONDARY, CREDIT, CAUSE) VALUES (2,2,3, 500, "Fontanero");
INSERT INTO TRANSACTIONS(CLIENT_ID, ACCCOUNT_ID, ACCOUNT_SECONDARY, CREDIT, CAUSE) VALUES (2,2,1, 3000, "Sueldo");

