DROP TABLE IF EXISTS CLIENT,
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS TRANSACTIONS;


CREATE TABLE CLIENT (
    CLIENT_ID INTEGER IDENTITY PRIMARY KEY,--id del CLIENTE
    ACCOUNT_ID INTEGER,
    AGE INTEGER NOT NULL;
    COUNTRY VARCHAR(255) NOT NULL,
    CLIENT_NAME VARCHAR(255) NOT NULL,
);

CREATE TABLE ACCOUNT  (
    CLIENT_ID INTEGER IDENTITY PRIMARY KEY,
    ACCOUNT_ID  INTEGER NOT NULL,
    DEPOSIT INTEGER,
    LOANS INTEGER,
);

CREATE TABLE TRANSACTIONS (
    CLIENT_ID INTEGER IDENTITY PRIMARY KEY,
    ACCCOUNT_ID INTEGER NOT NULL;
    ACCOUNT_SECONDARY INTEGER NOT NULL; --cuenta sobre la que se realiza la transaccion
    CREDIT INTEGER,--dinero de la transaccion
    CAUSE VARCHAR(255) NOT NULL,
);

